spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kotlin_application
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

spring.redis:
  host: localhost
  port: 6379
  password: null
  database: 0
