spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kotlin_application
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      enabled: true
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
