name: Push Docker Image

on:
  push:
    branches:
      - 'master'

jobs:
  push-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Push Docker Image
        run: ./gradlew jib -Djib.to.auth.username=${{secrets.DOCKERHUB_USER_NAME}} -Djib.to.auth.password=${{secrets.DOCKER_HUB_PASSWORD}}